## Numpy

In [11]:

import numpy as np
print(np.__version__)

# 1차원 배열
arr1 = np.array([1,2,3,4,5])
print("arr1")
print(f"{arr1}\n")

# 2차원 배열(행렬)
print("arr2")
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(arr2)


2.3.2
arr1
[1 2 3 4 5]

arr2
[[1 2 3]
 [4 5 6]]


In [2]:
# 0으로 채워진 배열
zeros = np.zeros((3,4))
print(zeros)

# 1로 채워진 배열
ones = np.ones((2,3))
print(ones)
# 특정 범위의 균일한 간격 배열
range_arr = np.arange(0,10,2)
print(range_arr)

# 선형 간격 배열
linear_space = np.linspace(0,1,5)
print(linear_space)

# 랜덤 배열
random_arr = np.random.random((2,3))
print(random_arr)
arr = np.array([[1,2,3],[4,5,6]])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.63396849 0.46067516 0.41167875]
 [0.13986949 0.78662749 0.86141006]]


In [3]:
# 주요 속성 
print(f"배열 차원: {arr.ndim}")
print(f'배열 형태: {arr.shape}')
print(f"배열 크기: {arr.size}")
print(f"요소 데이터 타입: {arr.dtype}")
print(f"각 요소 바이트 크기: {arr.itemsize}")
print(f"전체 배열 바이트 크기: {arr.nbytes}")
# 전치(행과 열 바꾸기)
print("원본 배열:")
print(arr)
print("전치 배열 (T):")
print(arr.T)

# 배열 형태 변경 (reshape)
arr1d = np.arange(12)
arr2d = arr1d.reshape(3,4)
print("변경 결과:")
print(arr2d)
# 배열 평탄화(1차원으로 변환)
print("평탄화 결과 (flatten)")
print(arr2d.flatten())

# 데이터 타입 변환
print("\n")
arr_float = arr.astype(np.float64)
print(f"타입 변환 후:{arr_float.dtype}")

배열 차원: 2
배열 형태: (2, 3)
배열 크기: 6
요소 데이터 타입: int64
각 요소 바이트 크기: 8
전체 배열 바이트 크기: 48
원본 배열:
[[1 2 3]
 [4 5 6]]
전치 배열 (T):
[[1 4]
 [2 5]
 [3 6]]
변경 결과:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
평탄화 결과 (flatten)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


타입 변환 후:float64


In [4]:
#통계 메서드
print('\n')
data = np.array([1,2,3,4,5])
print(f"sum:{data.sum()}")
print(f"mean:{data.mean()}")
print(f"min:{data.min()}")
print(f"max:{data.max()}")
print(f"std:{data.std()}")
print(f"var:{data.var()}")
print(f"cumsum:{data.cumsum()}")
# 조건 기반 인덱싱
arr = np.array([1,2,3,4,5])
print("짝수 요소만 선택")
print(arr[arr%2 ==0])



sum:15
mean:3.0
min:1
max:5
std:1.4142135623730951
var:2.0
cumsum:[ 1  3  6 10 15]
짝수 요소만 선택
[2 4]


In [5]:
# 배열 연산 메서드(행렬곱)
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print("행렬 곱셈 (dot)")
print(a.dot(b))

print("\n요소별 곱셈")
print(a*b)
# 1차원 배열 인덱싱
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print("--------")
# 2차원 배열 인덱싱
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2d[0,0])
print(arr2d[1,2])
print(arr2d[2,-1])

행렬 곱셈 (dot)
[[19 22]
 [43 50]]

요소별 곱셈
[[ 5 12]
 [21 32]]
10
50
--------
1
6
9


In [6]:
# 배열 슬라이싱

# 1차원 배열 슬라이싱
arr = np.array([10,20,30,40,50,60])
print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::2])
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print(arr2d[:2,1:3])
print("="*10)
print(arr2d[1:,:2])

# Numpy 브로드캐스팅
arr = np.array([1,2,3,4,5])
print(arr+10)
print("\n")
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10],[20]])
             
print(a+b)

[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[[2 3]
 [6 7]]
[[ 5  6]
 [ 9 10]]
[11 12 13 14 15]


[[11 12 13]
 [24 25 26]]


In [7]:
# 배열 형태 변경 
arr = np.arange(12)
reshaped2 = arr.reshape(3,4)
print(reshaped2)
print("\n")
reshaped3 = arr.reshape(3,-1)
print(reshaped3)
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

vertical = np.concatenate([a,b],axis = 0)
print(vertical)

horizontal = np.concatenate([a,b], axis = 1)
print(horizontal)

v_stack = np.vstack([a,b])
h_stack = np.hstack([a,b])
print(v_stack)
print(h_stack)

arr = np.arange(12).reshape(3,4)
print(f"{arr}")

#수평 분할 (행 기준)
h_split = np.split(arr, 3, axis = 0)
for i, split_arr in enumerate(h_split):
    print(f"분할{i}",split_arr)
    
#수직 분할 (열 기준)
v_split = np.split(arr, 2, axis = 1)
for i, split_arr in enumerate(v_split):
    print(f"분할{i}",split_arr)
# Numpy 응용 (데이터 필터링)
ages = np.array([23,13,45,56,23,45,44,78,55])

adult_filter = ages >18
print(adult_filter)

adults = ages[adult_filter]
print(adults)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
분할0 [[0 1 2 3]]
분할1 [[4 5 6 7]]
분할2 [[ 8  9 10 11]]
분할0 [[0 1]
 [4 5]
 [8 9]]
분할1 [[ 2  3]
 [ 6  7]
 [10 11]]
[ True False  True  True  True  True  True  True  True]
[23 45 56 23 45 44 78 55]


In [9]:
# 조건부 필터링 (한 줄로 작성)
young_filter = ages[(ages > 18) & (ages <=30)]
print(young_filter)
# 상황별 값 할당 (조건부 변경)
ticket_prices = np.zeros_like(ages)

# 나이에 따른 티켓 가격 할당
ticket_prices[ages < 18] = 5
ticket_prices[(ages >= 18) & (ages <= 59)] = 10
ticket_prices[ages >= 60] = 8
print(ticket_prices)

[23 23]
[10  5 10 10 10 10 10  8 10]


In [10]:
# 이미지 필터링

## Pandas

In [4]:
pip install pandas

  Using cached pandas-2.3.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (91 kB)
  Using cached numpy-2.3.2-cp312-cp312-macosx_14_0_arm64.whl.metadata (62 kB)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.3.2-cp312-cp312-macosx_11_0_arm64.whl (10.7 MB)
Using cached numpy-2.3.2-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd
print(pd.__version__)
# 기본 시리즈 생성
s = pd.Series([1,3,5,7,9])
print(s)
# 인덱스를 지정하여 시리즈 생성
s2 = pd.Series([10,20,30,40], index = ['a','b','c','d'])
print(s2)
# 딕셔너리로 시리즈 생성
population = {
    'Seoul':97774,
    'Busan': 3456,
    'Incheon' : 29345,
    'Daegu' : 2456
}

pop_series = pd.Series(population)
print(pop_series)

2.3.2
0    1
1    3
2    5
3    7
4    9
dtype: int64
a    10
b    20
c    30
d    40
dtype: int64
Seoul      97774
Busan       3456
Incheon    29345
Daegu       2456
dtype: int64


In [14]:
# 시리즈 생성 및 메소드
s = pd.Series([10,20,30,40,50,], index = ['a','b','c','d','e'])

# 기본 속성
print("값 배열:", s.values)
print("인덱스:", s.index)

# 기본 통계 메서드
print("평균:", s.mean())
print("합계", s.sum())
print("최소값",s.min() )
print("최대값", s.max())

값 배열: [10 20 30 40 50]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
평균: 30.0
합계 150
최소값 10
최대값 50


In [ ]:
# 데이터 접근
print("'c'인덱스의 값:", s['c'])
print("여러 인덱스의 값:", s[['a','c','e']])
# 조건부 필터링
print("30보다 큰 값" ,s[s>30])

# 데이터 변환
print("제곱근:", s.apply(np.sqrt))
print("2배 값:", s * 2)
print("제곱 값:", s ** 2)
# 결측치 확인 및 처리
s2 = pd.Series([10,np.nan, 30, np.nan, 50], index = ['a','b','c','d','e'])
print("결측치 여부:", s2.isna())
print("결측치 제거:", s2.dropna())
print("결측치 으로 채우기", s2.fillna(0))



### 1. DataFrame

In [15]:

# 데이터 프레임 생성 및 메서드

data = {
    'Name': ['jhon','anna','peter','linda', 'bob'],
    'age' : [28, 34, 35, 32, 45],
    'City': ['NY','Paris','Berlin','London','Tokyo'],
    'Salary':[500000,300000,20000,60000,10000]
        }
df = pd.DataFrame(data)
print(df)

    Name  age    City  Salary
0   jhon   28      NY  500000
1   anna   34   Paris  300000
2  peter   35  Berlin   20000
3  linda   32  London   60000
4    bob   45   Tokyo   10000


In [18]:
print(df.shape) # 행, 열 크기
print(df.columns) # 열 이름
print(df.index) # 행 인덱스
print(df.dtypes) # 데이터 타입

(5, 4)
Index(['Name', 'age', 'City', 'Salary'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
Name      object
age        int64
City      object
Salary     int64
dtype: object


In [19]:
# 데이터 확인
print(df.head(2))
print(df.tail(2))
print(df.describe())

   Name  age   City  Salary
0  jhon   28     NY  500000
1  anna   34  Paris  300000
    Name  age    City  Salary
3  linda   32  London   60000
4    bob   45   Tokyo   10000
             age         Salary
count   5.000000       5.000000
mean   34.800000  178000.000000
std     6.300794  215453.011118
min    28.000000   10000.000000
25%    32.000000   20000.000000
50%    34.000000   60000.000000
75%    35.000000  300000.000000
max    45.000000  500000.000000


In [24]:
# 데이터 접근
print(df['age'])
print(df[['Name','Salary']])
print(df.iloc[0:3])
print(df[df['age']>=30])

0    28
1    34
2    35
3    32
4    45
Name: age, dtype: int64
    Name  Salary
0   jhon  500000
1   anna  300000
2  peter   20000
3  linda   60000
4    bob   10000
    Name  age    City  Salary
0   jhon   28      NY  500000
1   anna   34   Paris  300000
2  peter   35  Berlin   20000
    Name  age    City  Salary
1   anna   34   Paris  300000
2  peter   35  Berlin   20000
3  linda   32  London   60000
4    bob   45   Tokyo   10000


### 2. Group By

In [8]:

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [75000, 65000, 80000, 90000, 60000, 78000],
    'Age': [28, 35, 32, 45, 30, 29],
    'Year': [2021, 2022, 2021, 2022, 2021, 2022]
})

# 기본 groupby 연산
dept_groups = df.groupby('Department')
print("부서별 평균 급여:")
dept_groups['Salary'].mean()


부서별 평균 급여:


Department
Finance    90000.000000
HR         62500.000000
IT         77666.666667
Name: Salary, dtype: float64

In [9]:
year_dept_groups = df.groupby(['Year','Department'])
print("\n연도별, 부서별 평균 급여:")
print(year_dept_groups['Salary'].mean())


연도별, 부서별 평균 급여:
Year  Department
2021  HR            60000.0
      IT            77500.0
2022  Finance       90000.0
      HR            65000.0
      IT            78000.0
Name: Salary, dtype: float64


In [10]:
print("\n부서별 급여 통계 요약:")
print(dept_groups['Salary'].describe())


부서별 급여 통계 요약:
            count          mean          std      min      25%      50%  \
Department                                                                
Finance       1.0  90000.000000          NaN  90000.0  90000.0  90000.0   
HR            2.0  62500.000000  3535.533906  60000.0  61250.0  62500.0   
IT            3.0  77666.666667  2516.611478  75000.0  76500.0  78000.0   

                75%      max  
Department                    
Finance     90000.0  90000.0  
HR          63750.0  65000.0  
IT          79000.0  80000.0  


In [11]:
# get_group 메소드 - 특정 그룹 선택
print("\nIT 부서 직원:")
print(dept_groups.get_group('IT'))


IT 부서 직원:
  Department Employee  Salary  Age  Year
0         IT    Alice   75000   28  2021
2         IT  Charlie   80000   32  2021
5         IT    Frank   78000   29  2022


In [23]:
# Group by 고급
# 1. 시간 기반 그룹화(월별, 분기별, 년도별)
df['Date'] = pd.date_range(start = '2022-01-01', periods = len(df), freq = 'M')
print("\n월별 평균 급여:")
print(df.groupby(df['Date'].dt.month)['Salary'].mean())

print("\n분기별 평균 급여:")
print(df.groupby(df['Date'].dt.quarter)['Salary'].mean())


월별 평균 급여:
Date
1    75000.0
2    65000.0
3    80000.0
4    90000.0
5    60000.0
6    78000.0
Name: Salary, dtype: float64

분기별 평균 급여:
Date
1    73333.333333
2    76000.000000
Name: Salary, dtype: float64


/var/folders/hs/81ncphtd2yzggndhp3qhjq400000gn/T/ipykernel_2064/841558530.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df['Date'] = pd.date_range(start = '2022-01-01', periods = len(df), freq = 'M')


In [27]:
# 2. 연속 변수의 범주화 후 그룹화 (구간별 그룹)
df['Age_group'] = pd.cut(df['Age'], bins = [20,30,40,50], labels = ['20대','30대','40대'])
print("\n연령대별 평균 급여")
print(df.groupby('Age_group')['Salary'].mean())



연령대별 평균 급여
Age_group
20대    71000.0
30대    72500.0
40대    90000.0
Name: Salary, dtype: float64


/var/folders/hs/81ncphtd2yzggndhp3qhjq400000gn/T/ipykernel_2064/1750282062.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('Age_group')['Salary'].mean())


In [34]:
#3. 크기 기반 분위수로 그룹화
df['Salary_Quantile'] = pd.qcut(df['Salary'], q = 3 , labels= ['Low','Medium', 'High'])
print("\n급여 분위수별 평균 나이")
print(df.groupby('Salary_Quantile')['Age'].mean())


급여 분위수별 평균 나이
Salary_Quantile
Low       32.5
Medium    28.5
High      38.5
Name: Age, dtype: float64


/var/folders/hs/81ncphtd2yzggndhp3qhjq400000gn/T/ipykernel_2064/160547932.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby('Salary_Quantile')['Age'].mean())


In [36]:
# 4. 사용자 정의 함수로 그룹화 - apply

def experience_level(age):
    if age < 30:
        return 'junior'
    elif age < 40:
        return 'Mid_level'
    else: 
        return 'Senior'
    
df['Experience'] = df['Age'].apply(experience_level)
print("\n경력 수준별 평균 급여")
print(df.groupby('Experience')['Salary'].mean())


경력 수준별 평균 급여
Experience
Mid_level    68333.333333
Senior       90000.000000
junior       76500.000000
Name: Salary, dtype: float64


In [42]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Score': [85, 92, 78, 96, 88, 73],
    'Attendance': [95, 80, 90, 75, 85, 92]
})

# 점수 기준 상위 3명
print("점수 기준 상위 3명")
print(df.nlargest(3, 'Score'))

# 출석률 기준 하위 2명
print("\n 출석률 기준 하위 2명")
print(df.nsmallest(2, 'Attendance'))

# 여러 열 기준 정렬 (다중 기준)
print("\n점수와 출석률 모두 높은 상위 3명:")
print(df.nlargest(3,['Score','Attendance']))

점수 기준 상위 3명
    Name  Score  Attendance
3  David     96          75
1    Bob     92          80
4    Eve     88          85

 출석률 기준 하위 2명
    Name  Score  Attendance
3  David     96          75
1    Bob     92          80

점수와 출석률 모두 높은 상위 3명:
    Name  Score  Attendance
3  David     96          75
1    Bob     92          80
4    Eve     88          85


### 3. 상관관계 및 공분산

In [44]:
print("\n점수와 출석률의 상관관계")
print(df[['Score','Attendance']].corr())
print("\n점수와 출석률의 공분산")
print(df[['Score','Attendance']].cov())


점수와 출석률의 상관관계
               Score  Attendance
Score       1.000000   -0.810441
Attendance -0.810441    1.000000

점수와 출석률의 공분산
                Score  Attendance
Score       74.266667  -53.266667
Attendance -53.266667   58.166667


### 4. Merge

In [47]:
# 샘플 데이터: 고객 정보
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'email': [
        'alice@example.com',
        'bob@example.com',
        'charlie@example.com',
        'david@example.com',
        'eve@example.com'
    ]
})

# 샘플 데이터: 주문 정보
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 3, 6, 7],
    'product': ['Laptop', 'Phone', 'Tablet', 'Monitor', 'Keyboard'],
    'amount': [1200, 800, 450, 300, 80]
})

print("고객정보")
print(customers)
print("\n주문 정보")
print(orders)


고객정보
   customer_id     name                email
0            1    Alice    alice@example.com
1            2      Bob      bob@example.com
2            3  Charlie  charlie@example.com
3            4    David    david@example.com
4            5      Eve      eve@example.com

주문 정보
   order_id  customer_id   product  amount
0       101            1    Laptop    1200
1       102            2     Phone     800
2       103            3    Tablet     450
3       104            6   Monitor     300
4       105            7  Keyboard      80


In [53]:
# 내부 조인 (inner join)
inner_join = pd.merge(customers, orders, on = 'customer_id')
print(f"내부 조인\n{inner_join}")

# 왼쪽 조인 (left join)
left_join = pd.merge(customers, orders, on = 'customer_id', how = 'left')
print(f"왼쪽 조인\n{left_join}")

# 오른쪽 조인 (right join)
right_join = pd.merge(customers, orders, on = 'customer_id', how = 'right')
print(f"오른쪽 조인\n{right_join}")

# 외부 조인 (outer join)
outer_join = pd.merge(customers, orders, on = 'customer_id', how = 'outer')
print(f"외부 조인\n{outer_join}")

내부 조인
   customer_id     name                email  order_id product  amount
0            1    Alice    alice@example.com       101  Laptop    1200
1            2      Bob      bob@example.com       102   Phone     800
2            3  Charlie  charlie@example.com       103  Tablet     450
왼쪽 조인
   customer_id     name                email  order_id product  amount
0            1    Alice    alice@example.com     101.0  Laptop  1200.0
1            2      Bob      bob@example.com     102.0   Phone   800.0
2            3  Charlie  charlie@example.com     103.0  Tablet   450.0
3            4    David    david@example.com       NaN     NaN     NaN
4            5      Eve      eve@example.com       NaN     NaN     NaN
오른쪽 조인
   customer_id     name                email  order_id   product  amount
0            1    Alice    alice@example.com       101    Laptop    1200
1            2      Bob      bob@example.com       102     Phone     800
2            3  Charlie  charlie@example.com       1

### 5. Concat

In [ ]:
# 데이터프레임 2개 생성
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5']
})

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)


DataFrame 1:
    A   B
0  A0  B0
1  A1  B1
2  A2  B2

DataFrame 2:
    A   B
0  A3  B3
1  A4  B4
2  A5  B5


In [55]:
import pandas as pd

# df1, df2가 이미 위에서 생성되어 있다고 가정

# 세로 방향으로 연결 (행 추가)
result_rows = pd.concat([df1, df2])
print("\n세로 연결 (행 추가):")
print(result_rows)

# 가로 방향으로 연결 (열 추가)
df3 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})

result_cols = pd.concat([df1, df3], axis=1)
print("\n가로 연결 (열 추가):")
print(result_cols)



세로 연결 (행 추가):
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
0  A3  B3
1  A4  B4
2  A5  B5

가로 연결 (열 추가):
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2


### 6. 데이터 전처리

In [60]:
import pandas as pd
import numpy as np

# 결측치가 있는 데이터프레임 생성
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan]
})

print("원본 데이터:")
print(df)

# 결측치 확인
print("\n결측치 여부:")
print(df.isna())


원본 데이터:
     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  2.0
2  NaN  3.0  3.0
3  4.0  4.0  NaN
4  5.0  5.0  NaN

결측치 여부:
       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False   True


In [73]:
# 결측치 개수 확인
print("\n열별 결측치 개수")
print(df.isna().sum())

# 결측치 처리 방법 1: 삭제
df_dropped = df.dropna()
print(f"\n삭제하기\n{df_dropped}")

# 결측치 처리 방법 2: 채우기
df_filled = df.fillna(0)
print(f"\n0으로 채우기\n{df_filled}")

# 결측치 처리 방법3: 열별 평균으로 채우기
df_mean = df.fillna(df.mean())
print(f"\n평균으로 채우기\n{df_mean}")


열별 결측치 개수
A    1
B    1
C    2
dtype: int64

삭제하기
     A    B    C
1  2.0  2.0  2.0

0으로 채우기
     A    B    C
0  1.0  0.0  1.0
1  2.0  2.0  2.0
2  0.0  3.0  3.0
3  4.0  4.0  0.0
4  5.0  5.0  0.0

평균으로 채우기
     A    B    C
0  1.0  3.5  1.0
1  2.0  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  2.0
4  5.0  5.0  2.0


### 7. 데이터 타입 변환

In [78]:
import pandas as pd

df = pd.DataFrame({
    'A': ['1', '2', '3', '4', '5'],
    'B': [1.1, 2.2, 3.3, 4.4, 5.5],
    'C': ['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01', '2020-05-01'],
    'D': ['True', 'False', 'True', 'False', 'True']
})

print("원본 데이터 타입:")
print(df.dtypes)
print(df.info())


원본 데이터 타입:
A     object
B    float64
C     object
D     object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      object 
 1   B       5 non-null      float64
 2   C       5 non-null      object 
 3   D       5 non-null      object 
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes
None


In [79]:
# 문자열 -> 정수 변환
df['A'] = df['A'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      int64  
 1   B       5 non-null      float64
 2   C       5 non-null      object 
 3   D       5 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes


In [82]:
# 문자열 -> 불리언 변환(주의사항 있음)
df['D'] = df['D'].astype(bool)
df.info() # 문자열 false도 true로 변환될 수 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      int64  
 1   B       5 non-null      float64
 2   C       5 non-null      object 
 3   D       5 non-null      bool   
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 257.0+ bytes


In [86]:
# 올바른 불리언 변환 방법
df_original = pd.DataFrame({
    'D':['True','False','True','False','True']
})

# 1. map 사용
df_original['D_correct1'] = df_original['D'].map({'True':True, 'False': False})
# 2. 조건문 사용
df_original['D_correct2'] = (df_original['D']== 'True')

df_original

D  D_correct1  D_correct2
0   True        True        True
1  False       False       False
2   True        True        True
3  False       False       False
4   True        True        True